a = int(input("Enter the first value for the equation: "))
b = int(input("Enter the second value for the equation: "))
c = int(input("Enter the third value for the equation: "))
d = int(input("Enter the fourth value for the equation: "))
result = (a+b)/(d+c)
print(f"the answer is {result}")